// Auto-generated by cdm install -- do not edit
import type { HexString, Binary, FixedSizeBinary } from "polkadot-api";

declare module "@dotdm/cdm" {
    interface CdmContracts {
        "@example/instagram": {
            methods: {
                createPost: { args: [description: string, photo_cid: string]; response: bigint };
                getPostCount: { args: [user: FixedSizeBinary<20>]; response: bigint };
                getPost: { args: [user: FixedSizeBinary<20>, index: bigint]; response: { description: string; photo_cid: string; timestamp: bigint } };
                getUserCount: { args: []; response: bigint };
                getUserAt: { args: [index: bigint]; response: FixedSizeBinary<20> };
            };
        };
    }
}
